### ISSUE TITLE
Propose data staging approach to kopp14

### ISSUE THREAD

**Issue by mturilli** [radical-collaboration/slrise#15]
The requirement is to save intermediate data to a dedicate `data` directory

**Comment by ggg121** [comment]
Thank you @mturilli for jumping on this issue.  Your rapid fix does address the need for an intermediate data directory for kopp14-icesheets stage1.task1, but the same fix would need to be applied to every task...which seems cumbersome.

After thinking about our discussion earlier, I agree that the intermediate data directory isn't really necessary.  I'm thinking I'll remove the hard-coded references to the relative `data` directory.  I'll set it up so that only relevant output from the tasks are downloaded back to the local machine and then apply the organizational scheme.

If you think this approach is appropriate, I'll go ahead and make the changes on the fix/issue14-15 branch and submit a pull request.

**Comment by mturilli** [comment]
Absolutely, please feel free to iterate on your code as you see it fit and no PR will be needed as you are the developer of this code. I will be the one making PRs when suggesting contributions for your review. Let me know whether you need further help with the testing.

**Comment by ggg121** [comment]
The commit referenced above takes care of this issue.  SLR module code now looks for input and produces output in the same directory in which the SLR module code is run.  I use the `download_output_data` feature within EnTK to download output from the SLR module and direct it to the user's experiment directory.
